# Generated by Django 3.2 on 2024-10-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241014_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.persona'),
        ),
    ]
