# Generated by Django 3.2 on 2024-10-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuarios_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='horario',
            name='bloque',
            field=models.CharField(default='08:30 - 10:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='asignatura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
