# Generated by Django 3.2 on 2024-10-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241016_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id',
            new_name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('Directivo', 'Directivo'), ('Profesor', 'Profesor'), ('Asistente', 'Asistente')], default='Profesor', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
