# Generated by Django 3.2 on 2024-11-01 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20241101_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='app.carpeta'),
        ),
    ]
