# Generated by Django 3.2 on 2024-11-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20241101_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpeta',
            old_name='creador',
            new_name='usuario',
        ),
    ]
