# Generated by Django 3.2 on 2024-11-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_carpeta_compartido_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='carpeta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='app.carpeta'),
        ),
    ]
