# Generated by Django 3.2 on 2024-11-17 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_carpeta_carpeta_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('destinatarios', models.CharField(choices=[('Directivo', 'Directivo'), ('Profesor', 'Profesor'), ('Asistente', 'Asistente')], max_length=10)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
