# Generated by Django 3.2 on 2024-10-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_horario_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='correo',
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(max_length=50),
        ),
    ]
