# Generated by Django 3.2 on 2024-10-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20241016_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariobase',
            name='bloque',
            field=models.CharField(choices=[('08:30 - 10:00', '08:30 - 10:00'), ('10:20 - 11:50', '10:20 - 11:50'), ('12:15 - 13:40', '12:15 - 13:40'), ('14:25 - 15:55', '14:25 - 15:55')], max_length=50),
        ),
    ]
