# Generated by Django 3.2 on 2024-10-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_horariobase_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariobase',
            name='asignatura',
            field=models.CharField(default='Sin asignatura', max_length=100),
        ),
        migrations.AlterField(
            model_name='horariobase',
            name='bloque',
            field=models.CharField(max_length=50),
        ),
    ]
