# Generated by Django 3.2 on 2024-10-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('reunion', 'Reunión'), ('evaluacion', 'Evaluación'), ('actividad', 'Actividad'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
