# Generated by Django 3.2 on 2024-10-29 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_archivo_carpeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='tamaño',
            new_name='tamano',
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='carpeta_padre',
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.carpeta'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
