# Generated by Django 3.2 on 2024-11-01 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20241029_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to=settings.AUTH_USER_MODEL),
        ),
    ]
