# Generated by Django 3.2 on 2024-11-04 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_archivo_compartido_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='compartido_con',
            field=models.ManyToManyField(blank=True, related_name='carpetas_compartidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
